#!/bin/sh
#
# amavisd: Amavis mail content checker
#
# chkconfig: 2345 80 30
# description: Amavis is a mail content checker that interfaces with email servers.

# Source function library
. /etc/rc.d/init.d/functions

prog=amavisd
exec=/usr/sbin/amavisd
config="/etc/amavisd/amavisd.conf"
pidfile=/run/amavisd/amavisd.pid
lockfile=/var/lock/subsys/$prog

start() {
    echo -n $"Starting $prog: "
    daemon --pidfile $pidfile $exec -c $config
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc -p $pidfile $prog -HUP
    retval=$?
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    status)
        status -p $pidfile $prog
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 2
esac

exit $?
