#!/bin/sh
#
# fail2ban: Fail2Ban Service
#
# chkconfig: 2345 80 20
# description: Fail2Ban scans log files and bans IPs that show malicious signs.

# Source function library
. /etc/rc.d/init.d/functions

prog=fail2ban
exec_start=/usr/bin/fail2ban-server
exec_stop=/usr/bin/fail2ban-client
pidfile=/run/fail2ban/fail2ban.pid
lockfile=/var/lock/subsys/$prog

start() {
    echo -n $"Starting $prog: "
    [ ! -d /run/fail2ban ] && mkdir -p /run/fail2ban
    daemon --pidfile $pidfile $exec_start -x start
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    $exec_stop stop
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    $exec_stop reload
    retval=$?
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    status)
        status -p $pidfile $prog
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 2
esac

exit $?
