#!/bin/sh
#
# opendkim: DomainKeys Identified Mail (DKIM) Milter
#
# chkconfig: 2345 80 30
# description: OpenDKIM provides DomainKeys Identified Mail (DKIM) signing and verification.

# Source function library
. /etc/rc.d/init.d/functions

prog=opendkim
exec=/usr/sbin/opendkim
config=/etc/sysconfig/opendkim
conf=/etc/opendkim.conf
pidfile=/var/run/opendkim/opendkim.pid
lockfile=/var/lock/subsys/$prog

[ -e $config ] && . $config

start() {
    echo -n $"Starting $prog: "
    daemon --pidfile $pidfile $exec -f $OPTIONS -x $conf
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc -p $pidfile $prog -USR1
    retval=$?
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    status)
        status -p $pidfile $prog
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 2
esac

exit $?
