production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: vmail
 pool: 5
 username: mail_administrator
 password: pas123
 host: localhost
 port: 3306
 socket:  /var/lib/mysql/mysql.sock
development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: vmail
 pool: 5
 username: mail_administrator
 password: pas123
 host: localhost
 port: 3306
 socket: /var/lib/mysql/mysql.sock
